services:
  - type: web
    name: casadarosa-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Jwt__Issuer
        value: CasaDaRosa
      - key: Jwt__Audience
        value: CasaDaRosaClients
      - key: Jwt__ExpirationInMinutes
        value: 60
      - key: Jwt__SecretKey
        sync: false
      - key: ConnectionStrings__DefaultConnection
        sync: false
